stages:
  - deploy

deploy_to_ftp:
  stage: deploy
  script:
    - apt-get update || true
    - apt-get install curl -y || true

    # Upload semua file (kecuali folder .git, vendor, node_modules, dll)
    - |
      PROJECT_DIR=project
      cd $PROJECT_DIR
      find . -type f ! -path "./.git/*" ! -path "./vendor/*" ! -path "./node_modules/*" | while read file; do
        remote_path="domains/mijurnal.com/public_html/api-pos/${file#./}"
        echo "Uploading $file to $remote_path"
        curl -s --ftp-create-dirs -T "$file" "ftp://$FTP_USER:$FTP_PASS@$FTP_HOST/$remote_path"
      done
  only:
    - main
