stages:
  - deploy

deploy_to_niagahoster:
  stage: deploy
  script:
    - apt-get update && apt-get install -y sshpass
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 65002 u752471078@88.223.89.189 "cd domains/mijurnal.com/public_html/api-pos && git pull origin main && composer install --no-interaction --prefer-dist && php artisan migrate --force"
  only:
    - main