stages:
  - deploy

deploy_to_niagahoster:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh git
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host server\n  HostName 88.223.89.189\n  User u752471078\n  Port 65002\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking=no" > ~/.ssh/config
  script:
    - ssh server "cd domains/mijurnal.com/public_html/api-pos && git pull origin main && composer install --no-interaction --prefer-dist && php artisan migrate --force"
  only:
    - main
