stages:
  - deploy

deploy_via_ftp:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache lftp
  script:
    - lftp -c "
        open -u $FTP_USER,$FTP_PASS ftp://$FTP_HOST;
        mirror -R ./ domains/mijurnal.com/public_html/api-pos;
      "
  only:
    - main