stages:
  - deploy

deploy_to_niagahoster:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -p 2289 -H 202.73.26.148 >> ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - |
      ssh -p 65002 u752471078@88.223.89.189 && 
      cd domains/mijurnal.com/public_html/api-pos && 
      git pull origin main && 
      composer2 install --no-interaction --prefer-dist && 
      php artisan migrate

    #- echo -e "Host server\n  HostName 88.223.89.189\n  User u752471078\n  Port 65002\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking=no" > ~/.ssh/config
    #- ssh server "cd domains/mijurnal.com/public_html/api-pos && git pull origin main && composer install --no-interaction --prefer-dist && php artisan migrate --force"
  only:
    - main